icons_format = " {icon} "

[theme]
theme = "dracula"

[icons]
icons = "awesome4"

[[block]]
block= "pomodoro"

[[block]]
block = "net"
format = "$icon "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "cpu"
interval = 2
format = " $icon $utilization "
format_alt = " $icon $barchart $frequency{ $boost|}($utilization) "
info_cpu = 50
warning_cpu = 70
critical_cpu = 90

[[block]]
block = "battery"
format = "$icon $percentage"
full_format = "$icon $percentage"
empty_format = "$icon $percentage"
charging_format = "$icon $percentage"
not_charging_format = "$icon $percentage"

[[block]]
block = "time"
interval = 60
format = " $timestamp.datetime(f:'%d.%m.%y %R') "
